[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.partitions = default.csv
board_build.flash_size = 4MB
board_upload.flash_size = 4MB

; Librării necesare pentru Web UI (Commit 2)
lib_deps = 
    mathieucarbou/ESPAsyncWebServer @ ^3.1.5
    mathieucarbou/AsyncTCP @ ^3.2.4

; Flag-uri de compilare pentru USB HID
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_HID_ON_BOOT=1