[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.partitions = default.csv
board_build.flash_size = 4MB
board_upload.flash_size = 4MB

; Flag-uri de compilare pentru a activa USB HID pe ESP32-S3
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_HID_ON_BOOT=1